### ISSUE TITLE
Release of Human Mask?

### ISSUE THREAD

**Issue by justopit** [FlyHighest/UnrealPerson#10]
Good Job, it achieves very good generalization ability for Re-ID. However, I noticed that you only released the picture, but don't release the human maks(parsing result). The mask is easy to get for virtual environment. It's better to release the human mask, I think. With human mask, the model learned maybe perform better.

**Comment by tyz1994** [comment]
The synthesis pipeline has the ability to produce segmentation masks. However, when we conduct experiments, we turn off this function to save the post-processing time. You may try the toolkit and generate some masks.

**Comment by tyz1994** [comment]
I've found some data with masks on my computer. They've been uploaded to google drive. 
  https://drive.google.com/drive/folders/1sQHVBWvDwn-SVJtMqZDpk2HK9g9tnZ1I?usp=sharing
