### ISSUE TITLE
How to get cloth textures

### ISSUE THREAD

**Issue by shijie2016** [FlyHighest/UnrealPerson#16]
Thanks for the sharing of your data synthesis toolkit. Could you please show me how to generate the black_patches subfolder in your clothes textures folder? I am trying to extract white patches using custom data. It seems that ccp_patches and df_patches also require additional annotations. Where can I find them? Thanks for your help.

**Comment by tyz1994** [comment]
You may use simple rules to classify the color type of a texture image. For instance, if you require black textures, just select those with average pixel values lower than 20 or some other thresholds.

**Comment by shijie2016** [comment]
Thanks!
