### ISSUE TITLE
Why --num_cam is 6?

### ISSUE THREAD

**Issue by TOM-tym** [FlyHighest/UnrealPerson#3]
When tranfer from Unreal to MSMT, the example code provided in README.MD is 
`python train_cbn.py --gpu_ids 0,1,2 --src unreal --tar msmt --num_cam 6 --name unreal2msmt --max_ep 60`
But, in train_cbn.py, line 29, says, --num_cam stands for the target camera number and in MSMT, there are 15 cameras.

**Comment by FlyHighest** [comment]
Thanks for your correction!
We made a mistake. num_cam=6 is for Market-1501.

**Comment by TOM-tym** [comment]
Thanks for your earily reply.
I will close this issue.
