### ISSUE TITLE
God Job! But when to release the synthesis toolkit?

### ISSUE THREAD

**Issue by senlinuc** [FlyHighest/UnrealPerson#4]

**Comment by FlyHighest** [comment]
Thanks for your interest in our synthesis tools. We are writing more scripts to make them easier to use. 
We'll let you know once we finish.

**Comment by tyz1994** [comment]
The toolkit and some necessary resources are ready. See this: https://github.com/FlyHighest/UnrealPerson/blob/main/SynthesisToolkit.md
