### ISSUE TITLE
About the cross-camera

### ISSUE THREAD

**Issue by ZelongZeng** [FlyHighest/UnrealPerson#6]
Hi @FlyHighest , thank you very much for your nice work.
I have a question. For images from different cameras, did you adjust the style of the images when capturing, or you just treat the images captured in different environments as if they captured from different cameras?

**Comment by FlyHighest** [comment]
Thanks for your question. We only adopt camera-based normalization in the network to align the "camera" data distribution. We did not do anything about different "environments".

**Comment by ZelongZeng** [comment]
Thank you for your reply.
Sorry, I mean, I want to make sure if there exist enough big camera/domain gap between the Unrealperson images with different cam ids? Did you apply any "method" to adjust it when you collect the dataset?
I did some experiments, I just train a baseline model on training data from a part of cams(for example, cam 1~3), and then test on test data from all cams. Compared with the same experiments on other opened dataset(Market, Duke), the evaluation is not so bad.

**Comment by FlyHighest** [comment]
When we collect the dataset, we did not apply any method to adjust the gaps among cameras.

**Comment by ZelongZeng** [comment]
OK. Thank you for your reply. I will close this issue.
