### ISSUE TITLE
Dataset upload to google drive

### ISSUE THREAD

**Issue by thuangb** [FlyHighest/UnrealPerson#8]
Can you upload the dataset to another drive such as google drive, onedrive so that non-chinese users can access ?

**Comment by tyz1994** [comment]
Sorry for the late reply. I have uploaded the datasets to google drive: https://drive.google.com/drive/folders/1sQHVBWvDwn-SVJtMqZDpk2HK9g9tnZ1I?usp=sharing

**Comment by thuangb** [comment]
Thanks!!! Really appreciate this
